stages:
  - test

image: maven:latest

services:
  - name: mariadb

variables:
  #Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: bugtracker
  MYSQL_USER: mantisbt
  MYSQL_PASSWORD: mantisbt

connect:
  image: mariadb

  script:
    - echo "SELECT 'OK';"
  tags:
    - docker


test:
  stage: test
  script:
    - mvn test
  tags:
    - ci